name: Update sponsors
on:
  push:
    branches: main
    paths: .github/workflows/update-sponsors.yml
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
jobs:
  update-sponsors:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm install -g sponsorkit
      - run: sponsorkit
        env:
          SPONSORKIT_GITHUB_TOKEN: ${{ secrets.SPONSORS_TOKEN }}
          SPONSORKIT_GITHUB_LOGIN: ${{ github.repository_owner }}
      - uses: EndBug/add-and-commit@v9
